const STORAGE_KEY = "music-chat-lab.chats.v1";
const ACTIVE_KEY = "music-chat-lab.active-chat.v1";
const SETTINGS_KEY = "music-chat-lab.api-settings.v1";
const API_KEY_KEYS = {
  anthropic:"music-chat-lab.api-key.anthropic.v1",
  openai:"music-chat-lab.api-key.openai.v1",
  google:"music-chat-lab.api-key.google.v1"
};
const COST_KEY = "music-chat-lab.cost-control.v1";
const providerModels = {anthropic:[{id:"claude-sonnet-5",label:"Claude Sonnet 5"},{id:"claude-opus-5",label:"Claude Opus 5"},{id:"claude-sonnet-4-6",label:"Claude Sonnet 4.6"}],openai:[{id:"gpt-5.6-sol",label:"GPT-5.6 Sol"},{id:"gpt-5.6-terra",label:"GPT-5.6 Terra"},{id:"gpt-5.6-luna",label:"GPT-5.6 Luna"}],google:[{id:"gemini-3.8-flash",label:"Gemini 3.8 Flash"},{id:"gemini-3.7-flash",label:"Gemini 3.7 Flash"},{id:"gemini-3.1-pro-preview",label:"Gemini 3.1 Pro Preview"}]};
let chats=loadChats(),activeChatId=localStorage.getItem(ACTIVE_KEY)||null,pendingFiles=[],sending=false;window.pendingFiles=pendingFiles;
const sidebar=document.getElementById("sidebar"),chatList=document.getElementById("chatList"),messages=document.getElementById("messages"),welcome=document.getElementById("welcome"),currentChatTitle=document.getElementById("currentChatTitle"),providerSelect=document.getElementById("providerSelect"),modelSelect=document.getElementById("modelSelect"),newChatButton=document.getElementById("newChatButton"),menuButton=document.getElementById("menuButton"),messageInput=document.getElementById("messageInput"),sendButton=document.getElementById("sendButton"),fileInput=document.getElementById("fileInput"),attachments=document.getElementById("attachments"),composerNote=document.getElementById("composerNote"),settingsButton=document.getElementById("settingsButton"),topSettingsButton=document.getElementById("topSettingsButton"),settingsDialog=document.getElementById("settingsDialog"),settingsForm=document.getElementById("settingsForm"),anthropicKeyInput=document.getElementById("anthropicKey"),openaiKeyInput=document.getElementById("openaiKey"),googleKeyInput=document.getElementById("googleKey"),clearKeysButton=document.getElementById("clearKeysButton");
function loadChats(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
function loadSettings(){
  let combined={};
  try{combined=JSON.parse(localStorage.getItem(SETTINGS_KEY))||{}}catch{combined={}}
  const result={
    anthropicKey:String(combined.anthropicKey||localStorage.getItem(API_KEY_KEYS.anthropic)||'').trim(),
    openaiKey:String(combined.openaiKey||localStorage.getItem(API_KEY_KEYS.openai)||'').trim(),
    googleKey:String(combined.googleKey||localStorage.getItem(API_KEY_KEYS.google)||'').trim()
  };
  if(result.anthropicKey||result.openaiKey||result.googleKey){
    try{
      localStorage.setItem(SETTINGS_KEY,JSON.stringify(result));
      if(result.anthropicKey)localStorage.setItem(API_KEY_KEYS.anthropic,result.anthropicKey);
      if(result.openaiKey)localStorage.setItem(API_KEY_KEYS.openai,result.openaiKey);
      if(result.googleKey)localStorage.setItem(API_KEY_KEYS.google,result.googleKey);
    }catch{}
  }
  return result;
}
function saveChats(){localStorage.setItem(STORAGE_KEY,JSON.stringify(chats))}
function saveSettings(s){
  const old=loadSettings();
  const next={
    anthropicKey:String(s?.anthropicKey||old.anthropicKey||'').trim(),
    openaiKey:String(s?.openaiKey||old.openaiKey||'').trim(),
    googleKey:String(s?.googleKey||old.googleKey||'').trim()
  };
  localStorage.setItem(SETTINGS_KEY,JSON.stringify(next));
  if(next.anthropicKey)localStorage.setItem(API_KEY_KEYS.anthropic,next.anthropicKey);
  if(next.openaiKey)localStorage.setItem(API_KEY_KEYS.openai,next.openaiKey);
  if(next.googleKey)localStorage.setItem(API_KEY_KEYS.google,next.googleKey);
  const verify=loadSettings();
  if((next.anthropicKey&&!verify.anthropicKey)||(next.openaiKey&&!verify.openaiKey)||(next.googleKey&&!verify.googleKey))throw new Error('API-Schlüssel konnten nicht dauerhaft gespeichert werden.');
  return verify;
}
function clearStoredApiKeys(){localStorage.removeItem(SETTINGS_KEY);Object.values(API_KEY_KEYS).forEach(k=>localStorage.removeItem(k))}
function makeId(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function currentChat(){return chats.find(c=>c.id===activeChatId)||null}
function createChat(){const c={id:makeId(),title:"Neuer Chat",createdAt:Date.now(),updatedAt:Date.now(),provider:providerSelect.value,model:modelSelect.value,messages:[]};chats.unshift(c);activeChatId=c.id;localStorage.setItem(ACTIVE_KEY,activeChatId);saveChats();pendingFiles=[];window.pendingFiles=pendingFiles;renderAll();messageInput.focus()}
function updateModels(preferredModel=null){const ms=providerModels[providerSelect.value]||[];modelSelect.innerHTML="";ms.forEach(m=>{const o=document.createElement("option");o.value=m.id;o.textContent=m.label;modelSelect.appendChild(o)});if(preferredModel&&ms.some(m=>m.id===preferredModel))modelSelect.value=preferredModel}
function providerLabel(p){return {anthropic:"Claude",openai:"OpenAI",google:"Gemini"}[p]||p}
function modelLabel(p,m){return providerModels[p]?.find(x=>x.id===m)?.label||m}
function renderChatList(){chatList.innerHTML="";[...chats].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(c=>{const b=document.createElement("button");b.className=`chat-item${c.id===activeChatId?" active":""}`;const d=new Date(c.updatedAt).toLocaleString("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});b.innerHTML='<div class="chat-item-title"></div><div class="chat-item-meta"></div>';b.querySelector(".chat-item-title").textContent=c.title;b.querySelector(".chat-item-meta").textContent=`${providerLabel(c.provider)} · ${d}`;b.addEventListener("click",()=>{activeChatId=c.id;localStorage.setItem(ACTIVE_KEY,activeChatId);pendingFiles=[];window.pendingFiles=pendingFiles;sidebar.classList.remove("open");renderAll()});chatList.appendChild(b)})}
function visibleText(t){return String(t||'').replace(/\n*\[MCL-(?:VORSCHLAG|QUELLEN):[^\]]*\]\s*/gi,'').trim()}
function renderMessages(){const c=currentChat();messages.innerHTML="";if(!c||!c.messages.length){messages.appendChild(welcome.cloneNode(true));return}c.messages.forEach(m=>{const r=document.createElement("div");r.className=`message-row ${m.role}${m.isError?" error":""}`;const meta=document.createElement("div");meta.className="message-meta";meta.textContent=m.role==="user"?"Du":m.isError?"Music Chat Lab":`${providerLabel(m.provider)} · ${modelLabel(m.provider,m.model)}`;const b=document.createElement("div");b.className=`message-bubble${m.thinking?" thinking":""}`;b.textContent=m.displayText??visibleText(m.text);if(m.files?.length)m.files.forEach(f=>{const chip=document.createElement("div");chip.className="file-chip";chip.textContent=`📎 ${f.name} · ${formatBytes(f.size)}${f.summary?` · ${f.summary}`:""}`;b.appendChild(document.createElement("br"));b.appendChild(chip)});r.append(meta,b);messages.appendChild(r)});messages.scrollTop=messages.scrollHeight}
function renderPendingFiles(){attachments.innerHTML="";pendingFiles.forEach((f,i)=>{const p=document.createElement("div");p.className="attachment-pill";const n=document.createElement("span");n.textContent=`${f.name} · ${formatBytes(f.size)}`;const x=document.createElement("button");x.textContent="×";x.addEventListener("click",()=>{pendingFiles.splice(i,1);window.pendingFiles=pendingFiles;renderPendingFiles()});p.append(n,x);attachments.appendChild(p)});window.pendingFiles=pendingFiles;window.dispatchEvent(new CustomEvent('mcl-pending-files-rendered',{detail:{files:[...pendingFiles]}}))}
function formatBytes(b){if(b<1024)return`${b} B`;if(b<1048576)return`${(b/1024).toFixed(1)} KB`;return`${(b/1048576).toFixed(1)} MB`}
function renderAll(){let c=currentChat();if(!c&&chats.length){activeChatId=chats[0].id;localStorage.setItem(ACTIVE_KEY,activeChatId);c=currentChat()}if(c){providerSelect.value=c.provider;updateModels(c.model);currentChatTitle.textContent=c.title}else{updateModels();currentChatTitle.textContent="Neuer Chat"}sendButton.disabled=sending;renderChatList();renderMessages();renderPendingFiles();renderCost()}
function apiKeyFor(p){const s=loadSettings();return {anthropic:s.anthropicKey,openai:s.openaiKey,google:s.googleKey}[p]||""}
function openSettings(){const s=loadSettings();anthropicKeyInput.value=s.anthropicKey||"";openaiKeyInput.value=s.openaiKey||"";googleKeyInput.value=s.googleKey||"";settingsDialog.showModal()}
function workspaceContext(){try{return window.MCLMidiWorkspaceContext?.()||''}catch{return''}}
function isProposalConfirmation(text,c){if(!/^(ja|ja bitte|mach das|mache das|genau|einverstanden|okay|ok|los|bitte|so machen|ausführen|führe (das|ihn|sie) aus)[.!\s]*$/i.test(String(text||'').trim()))return false;const a=[...(c?.messages||[])].reverse().find(m=>m.role==='assistant'&&!m.isError&&!m.thinking);return /\[MCL-VORSCHLAG:[a-z0-9]+\]/i.test(String(a?.text||''))}
const SCORE_BLOCK_RE=/\[MCL-ENGINE14-SCORE name=(?:"(?:[^"\\]|\\.)*")\]\n[\s\S]*?\n\[\/MCL-ENGINE14-SCORE\]/g;
const WORKSPACE_BLOCK_RE=/\n*--- MUSIKALISCHER ARBEITSTISCH ---[\s\S]*?--- ENDE MUSIKALISCHER ARBEITSTISCH ---\n*/g;
function scoreSummaryForApi(text){let s=String(text||'').trim();const fence=s.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fence)s=fence[1].trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<=a)return null;try{const x=JSON.parse(s.slice(a,b+1));if(!x||!Array.isArray(x.tr)||!x.tr.some(t=>Array.isArray(t.nt)))return null;return `Komposition erzeugt: ${x.ti||'Unbenannt'}. ${x.sm||''}`.trim()}catch{return null}}
function compactApiText(text,role){const summary=role==='assistant'?scoreSummaryForApi(text):null;if(summary)return summary;return String(text||'').replace(WORKSPACE_BLOCK_RE,'\n').replace(SCORE_BLOCK_RE,'').replace(/\n\n--- DATEIANHÄNGE ---\n?/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function normalizedMessages(c){return c.messages.filter(m=>!m.isError&&!m.thinking&&(m.role==="user"||m.role==="assistant")).map(m=>{let text=compactApiText(m.text||'',m.role);if(m.attachmentContext)text=`${text}${m.attachmentContext}`.trim();return{role:m.role,text}})}
function requestMessages(c){const out=normalizedMessages(c);if(c.__apiExtra){for(let i=out.length-1;i>=0;i--){if(out[i].role==='user'){out[i]={...out[i],text:`${out[i].text}${c.__apiExtra}`.trim()};break}}}return out}
function renderCost(){window.MCLUsageRender?.()}
async function prepareAttachments(files){const metadata=[],blocks=[];for(const file of files){let processed;try{processed=await window.MusicFileProcessing.fileToModelText(file)}catch(e){processed={kind:"error",summary:"Lesefehler",text:`[Datei ${file.name} konnte nicht verarbeitet werden: ${e?.message||e}]`}}metadata.push({name:file.name,size:file.size,type:file.type,kind:processed.kind,summary:processed.summary});blocks.push(processed.text)}return{metadata,modelText:blocks.length?`\n\n--- DATEIANHÄNGE ---\n${blocks.join("\n\n---\n")}`:""}}
async function callAnthropic(c,key){const history=requestMessages(c).map(m=>({role:m.role,content:m.text}));const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:c.model,max_tokens:4096,messages:history})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(apiErrorMessage(d,r.status));const t=(d.content||[]).filter(p=>p.type==="text").map(p=>p.text).join("\n").trim();if(!t)throw new Error("Claude hat keine Textantwort geliefert.");return t}
async function callOpenAI(c,key){const input=requestMessages(c).map(m=>({role:m.role,content:m.text}));const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${key}`},body:JSON.stringify({model:c.model,input,store:false})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(apiErrorMessage(d,r.status));const direct=typeof d.output_text==="string"?d.output_text:"",nested=(d.output||[]).flatMap(i=>i.content||[]).filter(p=>p.type==="output_text"||p.type==="text").map(p=>p.text||"").join("\n"),t=(direct||nested).trim();if(!t)throw new Error("OpenAI hat keine Textantwort geliefert.");return t}
async function callGoogle(c,key){const contents=requestMessages(c).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.text}]})),url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(c.model)}:generateContent`,r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(apiErrorMessage(d,r.status));const t=(d.candidates?.[0]?.content?.parts||[]).map(p=>p.text||"").join("\n").trim();if(!t)throw new Error("Gemini hat keine Textantwort geliefert.");return t}
function apiErrorMessage(d,s){return d?.error?.message||d?.message||`API-Fehler ${s}`}
async function requestAssistant(c){const k=apiKeyFor(c.provider);if(!k)throw new Error(`Für ${providerLabel(c.provider)} ist noch kein API-Schlüssel eingetragen.`);if(c.provider==="anthropic")return callAnthropic(c,k);if(c.provider==="openai")return callOpenAI(c,k);if(c.provider==="google")return callGoogle(c,k);throw new Error("Unbekannter KI-Anbieter.")}
async function sendMessage(){if(sending)return;const text=messageInput.value.trim();if(!text&&!pendingFiles.length)return;const p=providerSelect.value;if(!apiKeyFor(p)){composerNote.textContent=`Bitte zuerst den API-Schlüssel für ${providerLabel(p)} eintragen.`;openSettings();return}if(!currentChat())createChat();const c=currentChat();c.provider=providerSelect.value;c.model=modelSelect.value;sending=true;sendButton.disabled=true;composerNote.textContent=pendingFiles.length?"Dateien werden lokal analysiert …":`${providerLabel(c.provider)} · ${modelLabel(c.provider,c.model)}`;const prepared=await prepareAttachments(pendingFiles);const context=isProposalConfirmation(text,c)?'':workspaceContext();const persistentAttachment=prepared.metadata.some(f=>f.kind&&f.kind!=='midi')?prepared.modelText:'';const modelText=text.trim();c.messages.push({id:makeId(),role:"user",text:modelText,displayText:text,files:prepared.metadata,attachmentContext:persistentAttachment||undefined,createdAt:Date.now()});if(c.title==="Neuer Chat")c.title=text?text.slice(0,48):pendingFiles[0]?.name||"Datei-Chat";c.updatedAt=Date.now();saveChats();c.__apiExtra=`${context}${prepared.modelText}`;window.MCLUsageStartTurn?.({provider:c.provider,model:c.model});messageInput.value="";autoResize();pendingFiles=[];window.pendingFiles=pendingFiles;const thinking={id:makeId(),role:"assistant",provider:c.provider,model:c.model,text:`${providerLabel(c.provider)} antwortet …`,thinking:true,createdAt:Date.now()};c.messages.push(thinking);renderAll();try{c.messages=c.messages.filter(m=>m.id!==thinking.id);const answer=await requestAssistant(c);const usage=window.MCLUsageFinishTurn?.()||null;c.messages.push({id:makeId(),role:"assistant",provider:c.provider,model:c.model,text:answer,usage,createdAt:Date.now()})}catch(e){const usage=window.MCLUsageFinishTurn?.()||null;c.messages=c.messages.filter(m=>m.id!==thinking.id);c.messages.push({id:makeId(),role:"assistant",text:e?.message||String(e),usage,isError:true,createdAt:Date.now()})}finally{delete c.__apiExtra;sending=false;c.updatedAt=Date.now();saveChats();renderAll()}}
function autoResize(){messageInput.style.height="auto";messageInput.style.height=`${Math.min(messageInput.scrollHeight,180)}px`}
providerSelect.addEventListener("change",()=>{updateModels();const c=currentChat();if(c){c.provider=providerSelect.value;c.model=modelSelect.value;c.updatedAt=Date.now();saveChats();renderChatList()}});
modelSelect.addEventListener("change",()=>{const c=currentChat();if(c){c.model=modelSelect.value;c.updatedAt=Date.now();saveChats()}});
fileInput.addEventListener("change",e=>{pendingFiles.push(...Array.from(e.target.files));window.pendingFiles=pendingFiles;fileInput.value="";renderPendingFiles()});
settingsForm.addEventListener("submit",e=>{e.preventDefault();try{const saved=saveSettings({anthropicKey:anthropicKeyInput.value.trim(),openaiKey:openaiKeyInput.value.trim(),googleKey:googleKeyInput.value.trim()});anthropicKeyInput.value=saved.anthropicKey;openaiKeyInput.value=saved.openaiKey;googleKeyInput.value=saved.googleKey;composerNote.textContent=`API-Einstellungen gespeichert: Anthropic ${saved.anthropicKey?'ja':'nein'}, OpenAI ${saved.openaiKey?'ja':'nein'}, Google ${saved.googleKey?'ja':'nein'}.`;settingsDialog.close()}catch(err){composerNote.textContent=err?.message||String(err)}});
clearKeysButton.addEventListener("click",()=>{if(!confirm('Alle drei API-Schlüssel wirklich löschen?'))return;clearStoredApiKeys();anthropicKeyInput.value="";openaiKeyInput.value="";googleKeyInput.value="";composerNote.textContent='API-Schlüssel gelöscht.'});
settingsButton.addEventListener("click",openSettings);topSettingsButton.addEventListener("click",openSettings);newChatButton.addEventListener("click",createChat);menuButton.addEventListener("click",()=>sidebar.classList.toggle("open"));sendButton.addEventListener("click",sendMessage);messageInput.addEventListener("input",autoResize);messageInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));renderAll();