(()=>{
'use strict';
const GM=['acoustic_grand_piano','bright_acoustic_piano','electric_grand_piano','honkytonk_piano','electric_piano_1','electric_piano_2','harpsichord','clavinet','celesta','glockenspiel','music_box','vibraphone','marimba','xylophone','tubular_bells','dulcimer','drawbar_organ','percussive_organ','rock_organ','church_organ','reed_organ','accordion','harmonica','tango_accordion','acoustic_guitar_nylon','acoustic_guitar_steel','electric_guitar_jazz','electric_guitar_clean','electric_guitar_muted','overdriven_guitar','distortion_guitar','guitar_harmonics','acoustic_bass','electric_bass_finger','electric_bass_pick','fretless_bass','slap_bass_1','slap_bass_2','synth_bass_1','synth_bass_2','violin','viola','cello','contrabass','tremolo_strings','pizzicato_strings','orchestral_harp','timpani','string_ensemble_1','string_ensemble_2','synth_strings_1','synth_strings_2','choir_aahs','voice_oohs','synth_choir','orchestra_hit','trumpet','trombone','tuba','muted_trumpet','french_horn','brass_section','synth_brass_1','synth_brass_2','soprano_sax','alto_sax','tenor_sax','baritone_sax','oboe','english_horn','bassoon','clarinet','piccolo','flute','recorder','pan_flute','blown_bottle','shakuhachi','whistle','ocarina','lead_1_square','lead_2_sawtooth','lead_3_calliope','lead_4_chiff','lead_5_charang','lead_6_voice','lead_7_fifths','lead_8_bass__lead','pad_1_new_age','pad_2_warm','pad_3_polysynth','pad_4_choir','pad_5_bowed','pad_6_metallic','pad_7_halo','pad_8_sweep','fx_1_rain','fx_2_soundtrack','fx_3_crystal','fx_4_atmosphere','fx_5_brightness','fx_6_goblins','fx_7_echoes','fx_8_scifi','sitar','banjo','shamisen','koto','kalimba','bagpipe','fiddle','shanai','tinkle_bell','agogo','steel_drums','woodblock','taiko_drum','melodic_tom','synth_drum','reverse_cymbal','guitar_fret_noise','breath_noise','seashore','bird_tweet','telephone_ring','helicopter','applause','gunshot'];
let audio=null,master=null,currentScore=null,currentNodes=[],timer=null,startTime=0,startOffset=0,instruments=new Map(),loadGeneration=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const el=id=>document.getElementById(id);
function fmt(s){s=Math.max(0,Math.floor(Number(s)||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function ensureAudio(){if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.75;master.connect(audio.destination)}return audio}
function gmName(program,channel){return Number(channel)===9?'synth_drum':GM[clamp(Math.round(Number(program)||0),0,127)]||'acoustic_grand_piano'}
async function loadInstrument(program,channel){const key=Number(channel)===9?'drums':String(clamp(Math.round(Number(program)||0),0,127));if(instruments.has(key))return instruments.get(key);if(typeof window.Soundfont==='undefined')throw new Error('SoundFont-Modul konnte nicht geladen werden.');const name=gmName(program,channel);const p=window.Soundfont.instrument(ensureAudio(),name,{soundfont:'FluidR3_GM',format:'mp3',destination:master});instruments.set(key,p);try{return await p}catch(e){instruments.delete(key);if(name!=='acoustic_grand_piano'){const f=window.Soundfont.instrument(ensureAudio(),'acoustic_grand_piano',{soundfont:'FluidR3_GM',format:'mp3',destination:master});instruments.set(key,f);return await f}throw e}}
function scoreDuration(score){let max=0;(score?.tr||[]).forEach(t=>(t.nt||[]).forEach(n=>{const gate=Number.isFinite(Number(n[5]))?Number(n[5]):.95;max=Math.max(max,(Number(n[0])||0)+(Number(n[1])||0)*gate)}));return max*60/(Number(score?.bpm)||96)}
function stop(reset=false){currentNodes.forEach(n=>{try{n.stop?.()}catch{}});currentNodes=[];if(timer)clearInterval(timer);timer=null;if(reset){el('mainMidiSeek').value='0';el('mainMidiTime').textContent=`0:00 / ${fmt(scoreDuration(currentScore))}`;el('mainMidiStatus').textContent='Gestoppt.'}}
async function play(fromSeconds=null){if(!currentScore){el('mainMidiStatus').textContent='Bitte zuerst eine MIDI-Datei laden.';return}stop(false);const ac=ensureAudio();if(ac.state==='suspended')await ac.resume();const bpm=Number(currentScore.bpm)||96,spb=60/bpm,total=scoreDuration(currentScore);startOffset=fromSeconds==null?(Number(el('mainMidiSeek').value)||0)/1000*total:fromSeconds;const used=[],seen=new Set();for(const t of currentScore.tr||[]){const ch=clamp(Number(t.ch)||0,0,15),pg=clamp(Number(t.pg)||0,0,127),key=ch===9?'d':String(pg);if(!seen.has(key)){seen.add(key);used.push([pg,ch])}}el('mainMidiStatus').textContent='GM-Klänge werden geladen …';try{await Promise.all(used.map(([pg,ch])=>loadInstrument(pg,ch)))}catch(e){el('mainMidiStatus').textContent=`Player-Fehler: ${e.message||e}`;return}startTime=ac.currentTime+.08;for(const t of currentScore.tr||[]){const ch=clamp(Number(t.ch)||0,0,15),pg=clamp(Number(t.pg)||0,0,127),inst=await loadInstrument(pg,ch);for(const n of t.nt||[]){const st=(Number(n[0])||0)*spb,d=Math.max(.02,(Number(n[1])||.25)*spb),gate=Number.isFinite(Number(n[5]))?Number(n[5]):.95,en=st+d*gate;if(en<=startOffset)continue;const pitch=clamp(Math.round(Number(n[2])||60),0,127),vel=clamp(Number(n[3])||80,1,127),when=startTime+Math.max(0,st-startOffset),dur=Math.max(.03,en-Math.max(st,startOffset));try{const node=inst.play(pitch,when,{duration:dur,gain:Math.max(.02,Math.min(1,vel/127))});if(node)currentNodes.push(node)}catch{}}}el('mainMidiStatus').textContent='Wiedergabe';timer=setInterval(()=>{const pos=Math.min(total,startOffset+Math.max(0,ac.currentTime-startTime));el('mainMidiSeek').value=String(Math.round((total?pos/total:0)*1000));el('mainMidiTime').textContent=`${fmt(pos)} / ${fmt(total)}`;if(pos>=total){stop(false);el('mainMidiStatus').textContent='Wiedergabe beendet.'}},150)}
function parsedToScore(parsed,name){const ppq=Number(parsed.ppq)||480,bpm=Number(parsed.tempos?.[0]?.bpm)||96,tr=[];(parsed.trackData||[]).forEach(t=>{const channels=[...new Set((t.notes||[]).map(n=>Number(n.channel)||1))];channels.forEach(ch1=>{const notes=(t.notes||[]).filter(n=>(Number(n.channel)||1)===ch1);if(!notes.length)return;const pe=(t.programs||[]).find(p=>Number(p.channel)===ch1);tr.push({nm:t.name||'Track',ch:clamp(ch1-1,0,15),pg:clamp((Number(pe?.program)||1)-1,0,127),nt:notes.map(n=>[Number(n.start)/ppq,Math.max(1,Number(n.duration))/ppq,Number(n.note),Number(n.velocity),0,1])})})});return{ti:name,bpm,tr}}
async function loadFile(file){if(!file)return;const isMidi=/\.midi?$/i.test(file.name)||/midi/i.test(file.type||'');if(!isMidi)return;const generation=++loadGeneration;stop(false);el('mainMidiTitle').textContent=`Import: ${file.name}`;el('mainMidiStatus').textContent='MIDI wird geladen …';el('mainMidiSeek').value='0';try{const parser=window.MusicFileProcessing?.parseMidi;if(!parser)throw new Error('MIDI-Parser nicht geladen.');const score=parsedToScore(parser(await file.arrayBuffer()),file.name);if(generation!==loadGeneration)return;currentScore=score;const total=scoreDuration(currentScore);el('mainMidiSeek').value='0';el('mainMidiTime').textContent=`0:00 / ${fmt(total)}`;el('mainMidiStatus').textContent=`Import „${file.name}“ im Player bereit.`}catch(e){if(generation!==loadGeneration)return;currentScore=null;el('mainMidiTime').textContent='0:00 / 0:00';el('mainMidiStatus').textContent=`MIDI-Fehler: ${e.message||e}`}}
function scoreFromText(text){const s=String(text||'');const re=/\[MCL-ENGINE14-SCORE name=("(?:[^"\\]|\\.)*")\]\n([\s\S]*?)\n\[\/MCL-ENGINE14-SCORE\]/g;let m,last=null;while((m=re.exec(s)))try{last=JSON.parse(m[2])}catch{}if(last)return last;let raw=s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a)try{const x=JSON.parse(raw.slice(a,b+1));if(Array.isArray(x?.tr))return x}catch{}return null}
function getMessages(){try{const all=JSON.parse(localStorage.getItem('music-chat-lab.chats.v1'))||[],id=localStorage.getItem('music-chat-lab.active-chat.v1');return (all.find(c=>c.id===id)||{}).messages||[]}catch{return[]}}
function makeInlinePlayer(score){const box=document.createElement('div');box.className='mcl-midi-player';const total=scoreDuration(score);box.innerHTML='<button type="button">▶</button><button type="button">⏹</button><span class="mcl-time">0:00 / '+fmt(total)+'</span>';const buttons=box.querySelectorAll('button');buttons[0].onclick=()=>{currentScore=score;el('mainMidiTitle').textContent=`Chat: ${score.ti||'MIDI-Komposition'}`;play(0)};buttons[1].onclick=()=>stop(true);return box}
function enhanceMessages(){const rows=[...document.querySelectorAll('.message-row')],msgs=getMessages();rows.forEach((row,i)=>{if(row.dataset.gmPlayer==='1')return;const score=scoreFromText(msgs[i]?.text||'');if(!score)return;row.querySelector('.message-bubble')?.appendChild(makeInlinePlayer(score));row.dataset.gmPlayer='1'})}
el('mainMidiPlay')?.addEventListener('click',()=>play());el('mainMidiPause')?.addEventListener('click',()=>{if(!currentScore)return;const total=scoreDuration(currentScore),pos=(Number(el('mainMidiSeek').value)||0)/1000*total;stop(false);startOffset=pos;el('mainMidiStatus').textContent='Pause.'});el('mainMidiStop')?.addEventListener('click',()=>stop(true));el('mainMidiSeek')?.addEventListener('change',()=>{if(currentScore)play()});el('mainMidiVolume')?.addEventListener('input',()=>{ensureAudio();master.gain.value=(Number(el('mainMidiVolume').value)||75)/100});
const input=el('fileInput');if(input)input.addEventListener('change',e=>{const files=Array.from(e.target.files||[]).filter(x=>/\.midi?$/i.test(x.name)||/midi/i.test(x.type||''));const f=files.length?files[files.length-1]:null;if(f)loadFile(f)},true);
new MutationObserver(enhanceMessages).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('DOMContentLoaded',enhanceMessages);window.addEventListener('beforeunload',()=>stop(false));
})();