(()=>{
'use strict';
const PPQ=480;
const el=id=>document.getElementById(id);
function vlq(value){value=Math.max(0,Math.floor(value));let buffer=value&0x7f;const out=[];while((value>>=7)){buffer<<=8;buffer|=((value&0x7f)|0x80)}while(true){out.push(buffer&0xff);if(buffer&0x80)buffer>>=8;else break}return out}
function u16(n){return[(n>>8)&255,n&255]}
function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function bytes(s){return Array.from(new TextEncoder().encode(String(s)))}
function mtrk(events){events.sort((a,b)=>a.t-b.t||a.o-b.o);let last=0,out=[];for(const e of events){out.push(...vlq(e.t-last),...e.b);last=e.t}out.push(0,0xff,0x2f,0);return[...bytes('MTrk'),...u32(out.length),...out]}
function parseKeySignature(value){const MAJOR=['Cb','Gb','Db','Ab','Eb','Bb','F','C','G','D','A','E','B','F#','C#'],MINOR=['Ab','Eb','Bb','F','C','G','D','A','E','B','F#','C#','G#','D#','A#'];const raw=String(value||'').trim();if(!raw||/^frei$/i.test(raw))return null;const normalized=raw.replace(/♯/g,'#').replace(/♭/g,'b').replace(/-dur\b/i,' major').replace(/-moll\b/i,' minor').replace(/\bdur\b/i,' major').replace(/\bmoll\b/i,' minor').replace(/\s+/g,' ').trim();const minor=/\bminor\b/i.test(normalized)||/\bm\b/i.test(normalized);const root=normalized.split(' ')[0].replace(/^([a-g])([#b]?)$/i,(_,a,acc)=>a.toUpperCase()+acc);const roots=minor?MINOR:MAJOR,index=roots.findIndex(k=>k.toLowerCase()===root.toLowerCase());return index<0?null:{fifths:index-7,minor}}
function buildMidi(score){const chunks=[],bpm=Math.max(20,Math.min(300,Number(score?.bpm)||96)),ts=score?.ts||{n:4,d:4},mpqn=Math.round(60000000/bpm);const conductor=[{t:0,o:0,b:[0xff,0x51,0x03,(mpqn>>>16)&255,(mpqn>>>8)&255,mpqn&255]},{t:0,o:1,b:[0xff,0x58,0x04,Math.max(1,Number(ts.n)||4),Math.max(0,Math.round(Math.log2(Math.max(1,Number(ts.d)||4)))),24,8]}];const key=parseKeySignature(score?.k);if(key)conductor.push({t:0,o:2,b:[0xff,0x59,0x02,key.fifths&0xff,key.minor?1:0]});chunks.push(mtrk(conductor));(score?.tr||[]).forEach((tr,ix)=>{const ch=Math.max(0,Math.min(15,Number(tr.ch??ix)%16)),ev=[],nm=bytes(tr.nm||`Track ${ix+1}`);ev.push({t:0,o:0,b:[0xff,0x03,...vlq(nm.length),...nm]},{t:0,o:1,b:[0xc0|ch,Math.max(0,Math.min(127,Number(tr.pg)||0))]});(tr.ct||[]).forEach((c,i)=>ev.push({t:Math.max(0,Math.round(Number(c[0])*PPQ)),o:10+i,b:[0xb0|ch,Math.max(0,Math.min(127,Number(c[1])||0)),Math.max(0,Math.min(127,Number(c[2])||0))]}));(tr.nt||[]).forEach((n,i)=>{const start=Math.max(0,Math.round(Number(n[0])*PPQ)),dur=Math.max(1,Math.round(Number(n[1])*PPQ)),gate=Number.isFinite(Number(n[5]))?Number(n[5]):.95,end=Math.max(start+1,Math.round(start+dur*gate)),pitch=Math.max(0,Math.min(127,Math.round(Number(n[2])))),vel=Math.max(1,Math.min(127,Math.round(Number(n[3])||80)));ev.push({t:start,o:100+i*2,b:[0x90|ch,pitch,vel]},{t:end,o:101+i*2,b:[0x80|ch,pitch,0]})});chunks.push(mtrk(ev))});const header=[...bytes('MThd'),...u32(6),...u16(1),...u16(chunks.length),...u16(PPQ)];return new Blob([new Uint8Array([...header,...chunks.flat()])],{type:'audio/midi'})}
function filename(item){const base=String(item?.name||item?.score?.ti||'MusicChatLab').replace(/\.(mid|midi)$/i,'').replace(/[\\/:*?"<>|]+/g,'_').trim()||'MusicChatLab';return`${base}.mid`}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},2500)}
function activeItem(){const active=document.querySelector('.mcl-midi-slot.active');if(!active)return null;const slot=Number(active.dataset.slot)+1;return window.MCLMidiSlots?.get?.([slot])?.[0]||null}
function exportActive(){const item=activeItem(),status=el('mainMidiStatus');if(!item?.score){if(status)status.textContent='Bitte zuerst einen belegten Speicherplatz wählen.';return}try{const name=filename(item);download(buildMidi(item.score),name);if(status)status.textContent=`MIDI exportiert: ${name}`}catch(e){if(status)status.textContent=`MIDI-Exportfehler: ${e?.message||e}`}}
function start(){el('mainMidiExport')?.addEventListener('click',exportActive)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
