(()=>{
'use strict';
const GM=['acoustic_grand_piano','bright_acoustic_piano','electric_grand_piano','honkytonk_piano','electric_piano_1','electric_piano_2','harpsichord','clavinet','celesta','glockenspiel','music_box','vibraphone','marimba','xylophone','tubular_bells','dulcimer','drawbar_organ','percussive_organ','rock_organ','church_organ','reed_organ','accordion','harmonica','tango_accordion','acoustic_guitar_nylon','acoustic_guitar_steel','electric_guitar_jazz','electric_guitar_clean','electric_guitar_muted','overdriven_guitar','distortion_guitar','guitar_harmonics','acoustic_bass','electric_bass_finger','electric_bass_pick','fretless_bass','slap_bass_1','slap_bass_2','synth_bass_1','synth_bass_2','violin','viola','cello','contrabass','tremolo_strings','pizzicato_strings','orchestral_harp','timpani','string_ensemble_1','string_ensemble_2','synth_strings_1','synth_strings_2','choir_aahs','voice_oohs','synth_choir','orchestra_hit','trumpet','trombone','tuba','muted_trumpet','french_horn','brass_section','synth_brass_1','synth_brass_2','soprano_sax','alto_sax','tenor_sax','baritone_sax','oboe','english_horn','bassoon','clarinet','piccolo','flute','recorder','pan_flute','blown_bottle','shakuhachi','whistle','ocarina','lead_1_square','lead_2_sawtooth','lead_3_calliope','lead_4_chiff','lead_5_charang','lead_6_voice','lead_7_fifths','lead_8_bass__lead','pad_1_new_age','pad_2_warm','pad_3_polysynth','pad_4_choir','pad_5_bowed','pad_6_metallic','pad_7_halo','pad_8_sweep','fx_1_rain','fx_2_soundtrack','fx_3_crystal','fx_4_atmosphere','fx_5_brightness','fx_6_goblins','fx_7_echoes','fx_8_scifi','sitar','banjo','shamisen','koto','kalimba','bagpipe','fiddle','shanai','tinkle_bell','agogo','steel_drums','woodblock','taiko_drum','melodic_tom','synth_drum','reverse_cymbal','guitar_fret_noise','breath_noise','seashore','bird_tweet','telephone_ring','helicopter','applause','gunshot'];
const DR={35:'acoustic_bass_drum',36:'bass_drum_1',37:'side_stick',38:'acoustic_snare',39:'hand_clap',40:'electric_snare',41:'low_floor_tom',42:'closed_hi_hat',43:'high_floor_tom',44:'pedal_hi_hat',45:'low_tom',46:'open_hi_hat',47:'low_mid_tom',48:'hi_mid_tom',49:'crash_cymbal_1',50:'high_tom',51:'ride_cymbal_1',52:'chinese_cymbal',53:'ride_bell',54:'tambourine',55:'splash_cymbal',56:'cowbell',57:'crash_cymbal_2',58:'vibraslap',59:'ride_cymbal_2',60:'hi_bongo',61:'low_bongo',62:'mute_hi_conga',63:'open_hi_conga',64:'low_conga',65:'high_timbale',66:'low_timbale',67:'high_agogo',68:'low_agogo',69:'cabasa',70:'maracas',71:'short_whistle',72:'long_whistle',73:'short_guiro',74:'long_guiro',75:'claves',76:'hi_wood_block',77:'low_wood_block',78:'mute_cuica',79:'open_cuica',80:'mute_triangle',81:'open_triangle'};
let ac=null,master=null,current=null,cache=new Map(),pendingScores=new Map();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function scoreFromText(text){const s=String(text||'');const re=/\[MCL-ENGINE14-SCORE name=("(?:[^"\\]|\\.)*")\]\n([\s\S]*?)\n\[\/MCL-ENGINE14-SCORE\]/g;let m,last=null;while((m=re.exec(s)))try{last=JSON.parse(m[2])}catch{}if(last)return last;let raw=s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a)try{const x=JSON.parse(raw.slice(a,b+1));if(Array.isArray(x?.tr))return x}catch{}return null}
function getMessages(){try{const all=JSON.parse(localStorage.getItem('music-chat-lab.chats.v1'))||[],id=localStorage.getItem('music-chat-lab.active-chat.v1');return (all.find(c=>c.id===id)||{}).messages||[]}catch{return[]}}
function ensureAudio(){if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.75;master.connect(ac.destination)}if(ac.state==='suspended')ac.resume();return ac}
async function instrument(name){if(cache.has(name))return cache.get(name);const p=window.Soundfont.instrument(ensureAudio(),name,{soundfont:'FluidR3_GM',format:'mp3',destination:master});cache.set(name,p);try{return await p}catch(e){cache.delete(name);throw e}}
function duration(score){let d=0;(score.tr||[]).forEach(t=>(t.nt||[]).forEach(n=>d=Math.max(d,Number(n[0])+(Number(n[1])||0)*(Number(n[5])||.95))));return d*60/(Number(score.bpm)||96)}
function stopCurrent(){if(!current)return;(current.nodes||[]).forEach(n=>{try{n.stop?.()}catch{}});clearInterval(current.timer);current=null}
function fmt(s){s=Math.max(0,Math.floor(s||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
async function play(score,ui,offset=0){stopCurrent();ensureAudio();ui.status.textContent='GM-Klänge werden geladen …';const bpm=Number(score.bpm)||96,secBeat=60/bpm,total=duration(score),needed=new Set();(score.tr||[]).forEach(t=>(t.nt||[]).forEach(n=>needed.add(Number(t.ch)===9?(DR[Math.round(Number(n[2]))]||'woodblock'):GM[clamp(Math.round(Number(t.pg)||0),0,127)]));try{await Promise.all([...needed].map(instrument))}catch(e){ui.status.textContent='SoundFont konnte nicht geladen werden.';return}const startAt=ac.currentTime+.08,nodes=[],token=Symbol();current={token,score,ui,offset,startAt,nodes,total,timer:null};(score.tr||[]).forEach(t=>{const drum=Number(t.ch)===9,prog=GM[clamp(Math.round(Number(t.pg)||0),0,127)];(t.nt||[]).forEach(n=>{const abs=Number(n[0])*secBeat,dur=Math.max(.03,Number(n[1])*secBeat*(Number.isFinite(Number(n[5]))?Number(n[5]):.95));if(abs+dur<=offset)return;const name=drum?(DR[Math.round(Number(n[2]))]||'woodblock'):prog,when=startAt+Math.max(0,abs-offset),remaining=Math.max(.03,dur-Math.max(0,offset-abs)),gain=clamp((Number(n[3])||80)/127,0.03,1);instrument(name).then(ins=>{if(current?.token!==token)return;try{const node=ins.play(drum?60:Math.round(Number(n[2])),when,remaining,{gain});if(node)nodes.push(node)}catch{}})});});ui.status.textContent='Wiedergabe';current.timer=setInterval(()=>{if(!current||current.token!==token)return;const pos=offset+Math.max(0,ac.currentTime-startAt);ui.seek.value=Math.round(clamp(pos/Math.max(total,.001),0,1)*1000);ui.time.textContent=`${fmt(pos)} / ${fmt(total)}`;if(pos>=total){stopCurrent();ui.seek.value=1000;ui.time.textContent=`${fmt(total)} / ${fmt(total)}`;ui.status.textContent='Beendet.'}},150)}
function makePlayer(score){const box=document.createElement('div');box.className='mcl-midi-player';box.innerHTML='<button type="button">▶</button><button type="button">⏸</button><button type="button">⏹</button><input class="mcl-seek" type="range" min="0" max="1000" value="0"><span class="mcl-time"></span><label>🔊 <input class="mcl-vol" type="range" min="0" max="100" value="75"></label><span class="mcl-player-status">GM-Player bereit.</span>';const [p,pa,st]=box.querySelectorAll('button'),seek=box.querySelector('.mcl-seek'),time=box.querySelector('.mcl-time'),vol=box.querySelector('.mcl-vol'),status=box.querySelector('.mcl-player-status'),total=duration(score),ui={seek,time,status};time.textContent=`0:00 / ${fmt(total)}`;p.addEventListener('click',()=>play(score,ui,(Number(seek.value)||0)/1000*total));pa.addEventListener('click',()=>{if(current?.ui===ui){const pos=current.offset+Math.max(0,ac.currentTime-current.startAt);seek.value=Math.round(clamp(pos/Math.max(total,.001),0,1)*1000);stopCurrent();status.textContent='Pause.'}});st.addEventListener('click',()=>{if(current?.ui===ui)stopCurrent();seek.value=0;time.textContent=`0:00 / ${fmt(total)}`;status.textContent='Gestoppt.'});seek.addEventListener('change',()=>{if(current?.ui===ui)play(score,ui,Number(seek.value)/1000*total)});vol.addEventListener('input',()=>{ensureAudio();master.gain.value=Number(vol.value)/100});return box}
function pendingKey(f){return `${f.name}|${f.size}|${f.lastModified}`}
async function loadPendingScore(file){const key=pendingKey(file);if(pendingScores.has(key))return pendingScores.get(key);try{const p=window.MusicFileProcessing?.parseMidi;if(!p)return null;const parsed=p(await file.arrayBuffer()),ppq=Number(parsed.ppq)||480,bpm=Number(parsed.tempos?.[0]?.bpm)||96,tr=[];(parsed.trackData||[]).forEach(t=>{const channels=[...new Set((t.notes||[]).map(n=>Number(n.channel)||1))];channels.forEach(ch1=>{const notes=(t.notes||[]).filter(n=>(Number(n.channel)||1)===ch1);if(!notes.length)return;const pe=(t.programs||[]).find(x=>Number(x.channel)===ch1);tr.push({nm:t.name||'Track',ch:clamp(ch1-1,0,15),pg:clamp((Number(pe?.program)||1)-1,0,127),nt:notes.map(n=>[Number(n.start)/ppq,Math.max(1,Number(n.duration))/ppq,Number(n.note),Number(n.velocity),0,1])})})});if(!tr.length)return null;const score={ti:file.name,bpm,tr};pendingScores.set(key,score);return score}catch(e){console.error('MCL MIDI preview:',e);return null}}
async function enhancePending(){const host=document.getElementById('attachments');const files=window.pendingFiles;if(!host||!Array.isArray(files))return;const pills=[...host.querySelectorAll('.attachment-pill')];for(let i=0;i<pills.length;i++){const file=files[i],pill=pills[i];if(!file||pill.dataset.gmPending==='1'||!(/\.midi?$/i.test(file.name)||/midi/i.test(file.type||'')))continue;const score=await loadPendingScore(file);if(!score)continue;const wrap=document.createElement('div');wrap.className='mcl-pending-player';wrap.appendChild(makePlayer(score));pill.insertAdjacentElement('afterend',wrap);pill.dataset.gmPending='1'}}
function enhance(){const rows=[...document.querySelectorAll('.message-row')],msgs=getMessages();rows.forEach((row,i)=>{if(row.dataset.gmPlayer==='1')return;const score=scoreFromText(msgs[i]?.text||'');if(!score)return;row.querySelector('.message-bubble')?.appendChild(makePlayer(score));row.dataset.gmPlayer='1'});enhancePending()}
new MutationObserver(enhance).observe(document.documentElement,{subtree:true,childList:true});
window.addEventListener('mcl-pending-files-rendered',()=>setTimeout(enhancePending,0));
window.addEventListener('DOMContentLoaded',enhance);
window.addEventListener('beforeunload',stopCurrent);
})();