(()=>{
'use strict';
if(window.__mclExplicitModeV2)return;window.__mclExplicitModeV2=true;
const VERSION='2.0.0-alpha.2',nativeFetch=window.fetch.bind(window),CONCEPT_RE=/<MCL_CONCEPT>\s*([\s\S]*?)\s*<\/MCL_CONCEPT>/i;let forwardingCompose=false;window.MCLRequestMode='chat';
function setMode(mode){window.MCLRequestMode=mode==='compose'?'compose':'chat'}
function setIdea(text){const value=String(text||'').trim();if(!value)return;if(window.MCLCompositionIdea?.set)window.MCLCompositionIdea.set(value,{generated:true,source:'chat'});else{const e=document.getElementById('compositionIdeaInput');if(e)e.value=value}}
function providerFor(url){const u=String(url||'');if(u.includes('api.anthropic.com/v1/messages'))return'anthropic';if(u.includes('api.openai.com/v1/responses'))return'openai';if(u.includes('generativelanguage.googleapis.com/')&&u.includes(':generateContent'))return'google';return null}
function directive(mode){if(mode==='compose')return`AKTUELLER AUSFÜHRUNGSMODUS: BEARBEITEN.\nDer Nutzer hat ausdrücklich eine musikalische Bearbeitung vorhandenen Materials gewählt. Verwende nur das Material, das für diesen Auftrag tatsächlich bereitgestellt oder ausdrücklich bezeichnet wurde. Erzeuge die verlangte MIDI-Fassung jetzt; falls Notendaten fehlen, fordere sie mit <MCL_NEED> an. Die endgültige Antwort muss genau eine gültige <MCL_ACTION> enthalten.`;return`AKTUELLER AUSFÜHRUNGSMODUS: CHAT.\nDer Nutzer hat ausdrücklich Gespräch statt MIDI-Ausführung gewählt. Antworte auf den eigentlichen Inhalt des Nutzertexts. In diesem Zug darf keine <MCL_ACTION> ausgegeben und keine MIDI-Fassung verändert werden.\n\nWenn im Gespräch tatsächlich eine konkrete, später ausführbare Kompositions- oder Bearbeitungsidee entsteht, darfst du sie zusätzlich ganz am Ende als verborgenen Block <MCL_CONCEPT>kurze aktuelle Idee</MCL_CONCEPT> markieren. Das ist optional.`}
function inject(system,mode){return`${directive(mode)}\n\n${String(system||'')}`}
function patchBody(provider,body,mode){if(provider==='anthropic')body.system=inject(body.system,mode);else if(provider==='openai'){const input=Array.isArray(body.input)?body.input:[],first=input.findIndex(x=>x?.role==='system');if(first>=0)input[first]={...input[first],content:inject(input[first].content,mode)};else input.unshift({role:'system',content:directive(mode)});body.input=input}else if(provider==='google'){const si=body.systemInstruction&&typeof body.systemInstruction==='object'?body.systemInstruction:{parts:[]},parts=Array.isArray(si.parts)?si.parts.slice():[];if(parts.length)parts[0]={...parts[0],text:inject(parts[0]?.text,mode)};else parts.push({text:directive(mode)});body.systemInstruction={...si,parts}}return body}
function responseText(provider,d){if(provider==='anthropic')return(d?.content||[]).filter(x=>x?.type==='text').map(x=>x.text||'').join('').trim();if(provider==='openai'){if(typeof d?.output_text==='string'&&d.output_text.trim())return d.output_text.trim();return(d?.output||[]).flatMap(x=>x?.content||[]).filter(x=>x?.type==='output_text'||x?.type==='text').map(x=>x?.text||'').join('\n').trim()}return(d?.candidates?.[0]?.content?.parts||[]).map(x=>x?.text||'').join('\n').trim()}
function replaceResponseText(provider,d,text){const x=JSON.parse(JSON.stringify(d||{}));if(provider==='anthropic')x.content=[{type:'text',text}];else if(provider==='openai'){x.output_text=text;x.output=[{type:'message',role:'assistant',content:[{type:'output_text',text}]}]}else{x.candidates=x.candidates?.length?x.candidates:[{}];x.candidates[0]={...(x.candidates[0]||{}),content:{role:'model',parts:[{text}]}}}return x}
function jsonResponse(data,r){const h=new Headers(r.headers||{});h.set('content-type','application/json');return new Response(JSON.stringify(data),{status:r.status,statusText:r.statusText,headers:h})}
window.fetch=async function(input,init={}){const url=typeof input==='string'?input:input?.url||'',provider=providerFor(url);if(!provider||typeof init.body!=='string')return nativeFetch(input,init);let body;try{body=JSON.parse(init.body)}catch{return nativeFetch(input,init)}const mode=window.MCLRequestMode==='compose'?'compose':'chat',response=await nativeFetch(input,{...init,body:JSON.stringify(patchBody(provider,body,mode))});if(mode!=='chat'||!response.ok)return response;const d=await response.clone().json().catch(()=>null);if(!d)return response;const raw=responseText(provider,d),m=raw.match(CONCEPT_RE);if(!m)return response;setIdea(m[1]);return jsonResponse(replaceResponseText(provider,d,raw.replace(CONCEPT_RE,'').replace(/\n{3,}/g,'\n\n').trim()),response)};
function bindButtons(){const chat=document.getElementById('sendButton'),compose=document.getElementById('composeButton'),input=document.getElementById('messageInput');if(!chat||!compose||!input)return;chat.addEventListener('click',()=>{if(!forwardingCompose)setMode('chat')},true);compose.addEventListener('click',()=>{if(chat.disabled)return;if(!input.value.trim()){const note=document.getElementById('composerNote');if(note)note.textContent='Bitte den aktuellen Kompositionsauftrag eingeben.';return}setMode('compose');forwardingCompose=true;try{chat.click()}finally{forwardingCompose=false}},true);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey)setMode('chat')},true);const sync=()=>{compose.disabled=chat.disabled};sync();new MutationObserver(sync).observe(chat,{attributes:true,attributeFilter:['disabled']})}
bindButtons();window.MCLExplicitModeV2={version:VERSION,getMode:()=>window.MCLRequestMode,setMode};
})();
